import {
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CheckCircle2,
  ClipboardCheck,
  Compass,
  Cpu,
  Database,
  Factory,
  FileSearch,
  GitBranch,
  HelpCircle,
  Layers,
  Lightbulb,
  ListChecks,
  LucideProps,
  Mail,
  MessageCircle,
  RefreshCw,
  Rocket,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Sliders,
  TrendingUp,
  UploadCloud,
  UserCheck,
  Workflow,
} from "lucide-react";
import React from "react";

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  Brain,
  Cpu,
  BarChart3,
  Workflow,
  Layers,
  TrendingUp,
  CheckCircle2,
  Rocket,
  Building2,
  Briefcase,
  ShoppingBag,
  Landmark: Building2,
  Factory,
  ArrowUpRight,
  Lightbulb,
  Sliders,
  Database,
  GitBranch,
  RefreshCw,
  Compass,
  FileSearch,
  ListChecks,
  ClipboardCheck,
  ShieldAlert,
  Calculator,
  BookOpen,
  UserCheck,
  Calendar,
  Mail,
  MessageCircle,
  HelpCircle,
  ShieldCheck,
  Search,
  ArrowRight,
  UploadCloud,
};

export function MegaMenuIcon({ name, className }: { name: string; className?: string }) {
  const IconComponent = iconMap[name] || ArrowRight;
  return <IconComponent className={className} aria-hidden="true" />;
}
